import {
  ArrowUp,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleDot,
  Copy,
  CornerUpLeft,
  Ellipsis,
  FolderOpen,
  Gauge,
  History,
  ListPlus,
  LoaderCircle,
  PanelLeft,
  Paperclip,
  Play,
  RefreshCw,
  RotateCcw,
  Search,
  Square,
  SquarePen,
  Trash2,
  Unplug,
  Wrench,
  X,
} from "lucide-react";

/** Canonical icons for renderer actions; use these instead of glyphs or local SVGs. */
export const iconByAction = {
  abort: Square,
  attach: Paperclip,
  close: X,
  copyDiagnostics: Copy,
  deleteSession: Trash2,
  dismissDrawer: X,
  expand: ChevronRight,
  collapse: ChevronDown,
  followUp: ListPlus,
  newSession: SquarePen,
  openProject: FolderOpen,
  overflow: Ellipsis,
  refresh: RefreshCw,
  reopenSession: History,
  retry: RotateCcw,
  runCommand: Play,
  search: Search,
  send: ArrowUp,
  sidebar: PanelLeft,
  steer: CornerUpLeft,
  success: Check,
  error: CircleAlert,
  usage: Gauge,
  waiting: CircleDot,
  working: LoaderCircle,
  tool: Wrench,
  disconnectRuntime: Unplug,
} as const;

export {
  ArrowUp,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleDot,
  Copy,
  CornerUpLeft,
  Ellipsis,
  FolderOpen,
  Gauge,
  History,
  ListPlus,
  LoaderCircle,
  PanelLeft,
  Paperclip,
  Play,
  RefreshCw,
  RotateCcw,
  Search,
  Square,
  SquarePen,
  Trash2,
  Unplug,
  Wrench,
  X,
};
export type { LucideIcon } from "lucide-react";
