import fs from "node:fs/promises";
import path from "node:path";

/** Environment variable containing `tcp:127.0.0.1:<port>` or `unix:/path`. */
export const DECK_DELEGATE_ENDPOINT_ENV = "DECK_DELEGATE_ENDPOINT";
/** Per-Pi-process capability; never put this value in a session message. */
export const DECK_DELEGATE_CAPABILITY_ENV = "DECK_DELEGATE_CAPABILITY";
export const DECK_DELEGATE_PROTOCOL_VERSION = 1;

export interface DeckDelegateRequest {
  version: typeof DECK_DELEGATE_PROTOCOL_VERSION;
  type: "delegate";
  capability: string;
  toolCallId: string;
  task: string;
  name?: string;
}

export interface DeckDelegateLifecycleMessage {
  version: typeof DECK_DELEGATE_PROTOCOL_VERSION;
  type: "lifecycle";
  toolCallId: string;
  status: "started" | "progress" | "input-needed";
  message?: string;
}

export interface DeckDelegateResultMessage {
  version: typeof DECK_DELEGATE_PROTOCOL_VERSION;
  type: "result";
  toolCallId: string;
  ok: boolean;
  text: string;
  details?: unknown;
}

/**
 * The JSONL protocol contract for Deck's delegate endpoint.
 *
 * Pi writes exactly one {@link DeckDelegateRequest} per connection. Deck may
 * write zero or more lifecycle messages and exactly one result message. All
 * messages are UTF-8 JSON values terminated by a single LF. There intentionally
 * is no server implementation here: Deck owns the endpoint and capability.
 */
export type DeckDelegateWireMessage =
  | DeckDelegateRequest
  | DeckDelegateLifecycleMessage
  | DeckDelegateResultMessage;

/**
 * Write an extension which has no imports from this application. Pi resolves
 * its own bundled `@earendil-works/pi-coding-agent` and `typebox` packages.
 */
export async function writeDeckDelegateExtension(outputPath: string): Promise<void> {
  if (!outputPath.trim()) {
    throw new Error("An extension output path is required");
  }

  await fs.mkdir(path.dirname(path.resolve(outputPath)), { recursive: true });
  await fs.writeFile(outputPath, DECK_DELEGATE_EXTENSION_SOURCE, "utf8");
}

/** Self-contained TypeScript source written by {@link writeDeckDelegateExtension}. */
export const DECK_DELEGATE_EXTENSION_SOURCE = String.raw`// Generated by Pi Deck. Load explicitly with: pi --extension ./deck-delegate.ts
// Deck delegate JSONL protocol v1. The endpoint is supplied by Deck; this file does not implement it.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import net, { type Socket } from "node:net";

export const DECK_DELEGATE_PROTOCOL_VERSION = 1;
export const DECK_DELEGATE_ENDPOINT_ENV = "DECK_DELEGATE_ENDPOINT";
export const DECK_DELEGATE_CAPABILITY_ENV = "DECK_DELEGATE_CAPABILITY";
const MAX_LINE_BYTES = 64 * 1024;
const MAX_BUFFER_BYTES = MAX_LINE_BYTES + 1;
const MAX_TASK_CHARS = 32 * 1024;
const MAX_NAME_CHARS = 256;
const CONNECT_TIMEOUT_MS = 30_000;

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export interface DeckDelegateRequest {
  version: 1;
  type: "delegate";
  capability: string;
  toolCallId: string;
  task: string;
  name?: string;
}
export interface DeckDelegateLifecycleMessage {
  version: 1;
  type: "lifecycle";
  toolCallId: string;
  status: "started" | "progress" | "input-needed";
  message?: string;
}
export interface DeckDelegateResultMessage {
  version: 1;
  type: "result";
  toolCallId: string;
  ok: boolean;
  text: string;
  details?: JsonValue;
}
export type DeckDelegateWireMessage = DeckDelegateRequest | DeckDelegateLifecycleMessage | DeckDelegateResultMessage;

type Endpoint = { kind: "tcp"; port: number } | { kind: "unix"; path: string };

function configuration(): { endpoint: Endpoint; capability: string } {
  const rawEndpoint = process.env[DECK_DELEGATE_ENDPOINT_ENV];
  const capability = process.env[DECK_DELEGATE_CAPABILITY_ENV];
  if (!rawEndpoint) throw new Error("Deck delegate endpoint is not configured");
  // Capabilities are opaque printable tokens; reject whitespace/control characters so they cannot frame JSONL.
  if (!capability || capability.length < 16 || capability.length > 512 || !/^[!-~]+$/.test(capability)) {
    throw new Error("Deck delegate capability is missing or invalid");
  }
  const tcp = /^tcp:127\\.0\\.0\\.1:([0-9]{1,5})$/.exec(rawEndpoint);
  if (tcp) {
    const port = Number(tcp[1]);
    if (port >= 1 && port <= 65535) return { endpoint: { kind: "tcp", port }, capability };
  }
  if (rawEndpoint.startsWith("unix:/") && rawEndpoint.length <= 4096 && !/[\\r\\n\\0]/.test(rawEndpoint)) {
    return { endpoint: { kind: "unix", path: rawEndpoint.slice("unix:".length) }, capability };
  }
  throw new Error("Deck delegate endpoint must be tcp:127.0.0.1:<port> or unix:/<path>");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function lifecycle(value: unknown, toolCallId: string): DeckDelegateLifecycleMessage | undefined {
  if (!isRecord(value) || value.version !== 1 || value.type !== "lifecycle" || value.toolCallId !== toolCallId) return undefined;
  if (value.status !== "started" && value.status !== "progress" && value.status !== "input-needed") return undefined;
  if (value.message !== undefined && (typeof value.message !== "string" || value.message.length > MAX_TASK_CHARS)) return undefined;
  return value as DeckDelegateLifecycleMessage;
}

function result(value: unknown, toolCallId: string): DeckDelegateResultMessage | undefined {
  if (!isRecord(value) || value.version !== 1 || value.type !== "result" || value.toolCallId !== toolCallId) return undefined;
  if (typeof value.ok !== "boolean" || typeof value.text !== "string" || value.text.length > MAX_TASK_CHARS) return undefined;
  return value as DeckDelegateResultMessage;
}

function writeJsonLine(socket: Socket, value: DeckDelegateRequest): void {
  const encoded = Buffer.from(JSON.stringify(value) + "\\n", "utf8");
  if (encoded.byteLength > MAX_LINE_BYTES) throw new Error("Delegate request exceeds JSONL size limit");
  socket.write(encoded);
}

function relay(pi: ExtensionAPI, message: DeckDelegateLifecycleMessage | DeckDelegateResultMessage): void {
  const inputNeeded = message.type === "lifecycle" && message.status === "input-needed";
  const text = message.type === "result" ? message.text : (message.message || message.status);
  try {
    pi.sendMessage({
      customType: "deck_delegate",
      content: (inputNeeded ? "Deck child needs input: " : "Deck child result: ") + text,
      display: true,
      details: { version: 1, type: message.type, toolCallId: message.toolCallId, status: message.type === "lifecycle" ? message.status : undefined, ok: message.type === "result" ? message.ok : undefined },
    }, { deliverAs: "steer", triggerTurn: true });
  } catch {
    // A relay failure must not orphan or change the actual delegate result.
  }
}

function delegate(pi: ExtensionAPI, request: DeckDelegateRequest, endpoint: Endpoint, signal: AbortSignal): Promise<DeckDelegateResultMessage> {
  return new Promise((resolve, reject) => {
    const socket = endpoint.kind === "tcp"
      ? net.createConnection({ host: "127.0.0.1", port: endpoint.port })
      : net.createConnection({ path: endpoint.path });
    let buffer = Buffer.alloc(0);
    let settled = false;
    const timer = setTimeout(() => fail(new Error("Deck delegate connection timed out")), CONNECT_TIMEOUT_MS);
    const cleanup = () => {
      clearTimeout(timer);
      signal.removeEventListener("abort", aborted);
      socket.removeAllListeners();
      if (!socket.destroyed) socket.destroy();
    };
    const succeed = (message: DeckDelegateResultMessage) => {
      if (settled) return;
      settled = true;
      cleanup();
      relay(pi, message);
      resolve(message);
    };
    const fail = (error: Error) => {
      if (settled) return;
      settled = true;
      cleanup();
      reject(error);
    };
    const aborted = () => fail(new Error("Deck delegate cancelled"));
    const onData = (chunk: Buffer) => {
      buffer = Buffer.concat([buffer, chunk]);
      if (buffer.byteLength > MAX_BUFFER_BYTES) return fail(new Error("Deck delegate JSONL buffer exceeds size limit"));
      for (;;) {
        const newline = buffer.indexOf(10);
        if (newline < 0) return;
        const line = buffer.subarray(0, newline);
        buffer = buffer.subarray(newline + 1);
        if (line.byteLength > MAX_LINE_BYTES) return fail(new Error("Deck delegate JSONL line exceeds size limit"));
        let parsed: unknown;
        try { parsed = JSON.parse(line.toString("utf8")); } catch { return fail(new Error("Deck delegate sent invalid JSONL")); }
        const event = lifecycle(parsed, request.toolCallId);
        if (event) { if (event.status === "input-needed") relay(pi, event); continue; }
        const final = result(parsed, request.toolCallId);
        if (final) return succeed(final);
        return fail(new Error("Deck delegate sent an invalid protocol message"));
      }
    };
    socket.once("connect", () => {
      try { writeJsonLine(socket, request); } catch (error) { fail(error instanceof Error ? error : new Error("Unable to write delegate request")); }
    });
    socket.on("data", onData);
    socket.once("error", (error) => fail(error));
    socket.once("close", () => { if (!settled) fail(new Error("Deck delegate connection closed without a result")); });
    signal.addEventListener("abort", aborted, { once: true });
    if (signal.aborted) aborted();
  });
}

export default function deckDelegateExtension(pi: ExtensionAPI): void {
  pi.registerTool({
    name: "deck_delegate",
    label: "Delegate to Deck child",
    description: "Delegate an interactive child task to Pi Deck.",
    parameters: Type.Object({
      task: Type.String({ minLength: 1, maxLength: MAX_TASK_CHARS, description: "Task for the Deck child" }),
      name: Type.Optional(Type.String({ minLength: 1, maxLength: MAX_NAME_CHARS, description: "Optional child name" })),
    }),
    async execute(toolCallId, params, signal) {
      try {
        const config = configuration();
        const request: DeckDelegateRequest = { version: 1, type: "delegate", capability: config.capability, toolCallId, task: params.task, ...(params.name ? { name: params.name } : {}) };
        const final = await delegate(pi, request, config.endpoint, signal);
        return { content: [{ type: "text", text: final.text }], details: { ok: final.ok, serverDetails: final.details } };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Deck delegate failed";
        return { content: [{ type: "text", text: "Deck delegation failed: " + message }], details: { ok: false, error: message } };
      }
    },
  });
}
`;
