import fs from "node:fs/promises";
import path from "node:path";

/** Environment variable containing `tcp:127.0.0.1:<port>` or `unix:/path`. */
export const DECK_DELEGATE_ENDPOINT_ENV = "DECK_DELEGATE_ENDPOINT";
/** Per-Pi-process capability; never put this value in a session message. */
export const DECK_DELEGATE_CAPABILITY_ENV = "DECK_DELEGATE_CAPABILITY";
/** Parent-only binding carried in the extension process environment. */
export const DECK_DELEGATE_PARENT_RUNTIME_ENV = "DECK_DELEGATE_PARENT_RUNTIME";
export const DECK_DELEGATE_PROTOCOL_VERSION = 1;

export interface DeckDelegateRequest {
  version: typeof DECK_DELEGATE_PROTOCOL_VERSION;
  type: "delegate";
  capability: string;
  toolCallId: string;
  task: string;
  name?: string;
  action?: "provide_input";
  taskNumber?: number;
  input?: string;
}

export interface DeckDelegateLifecycleMessage {
  version: typeof DECK_DELEGATE_PROTOCOL_VERSION;
  type: "lifecycle";
  toolCallId: string;
  /** Stable public task routing key; never a child/session identity. */
  taskNumber?: number;
  status: "started" | "progress" | "input-needed";
  message?: string;
}

export interface DeckDelegateResultMessage {
  version: typeof DECK_DELEGATE_PROTOCOL_VERSION;
  type: "result";
  toolCallId: string;
  ok: boolean;
  text: string;
  details?: unknown;
}

/** Authenticated extension-to-host query for the current parent mode. */
export interface DeckDelegateModeQuery {
  version: typeof DECK_DELEGATE_PROTOCOL_VERSION;
  type: "mode-query";
  requestId: string;
}

export interface DeckDelegateModeState {
  version: typeof DECK_DELEGATE_PROTOCOL_VERSION;
  type: "mode-state";
  requestId: string;
  mode: "sequential" | "parallel";
}

/**
 * The JSONL protocol contract for Deck's delegate endpoint.
 *
 * Pi writes exactly one {@link DeckDelegateRequest} per connection. Deck may
 * write zero or more lifecycle messages and exactly one result message. All
 * messages are UTF-8 JSON values terminated by a single LF. There intentionally
 * is no server implementation here: Deck owns the endpoint and capability.
 */
export type DeckDelegateWireMessage =
  | DeckDelegateRequest
  | DeckDelegateLifecycleMessage
  | DeckDelegateResultMessage;

/**
 * Write an extension which has no imports from this application. Pi resolves
 * its own bundled `@earendil-works/pi-coding-agent` and `typebox` packages.
 */
export async function writeDeckDelegateExtension(
  outputPath: string,
): Promise<void> {
  if (!outputPath.trim()) {
    throw new Error("An extension output path is required");
  }

  await fs.mkdir(path.dirname(path.resolve(outputPath)), { recursive: true });
  await fs.writeFile(outputPath, DECK_DELEGATE_EXTENSION_SOURCE, "utf8");
}

/**
 * Write a test-only companion extension which invokes the generated tool
 * definition directly. This exercises Pi's real extension loader and the
 * generated tool's bridge protocol without asking a model to choose a tool.
 */
export async function writeDeckDelegateAcceptanceHarness(
  outputPath: string,
  delegateExtensionPath: string,
): Promise<void> {
  if (!outputPath.trim() || !delegateExtensionPath.trim()) {
    throw new Error("Harness and delegate extension paths are required");
  }

  await fs.mkdir(path.dirname(path.resolve(outputPath)), { recursive: true });
  await fs.writeFile(
    outputPath,
    `// Generated Pi Deck E2E acceptance harness. Never load outside E2E.\nimport type { ExtensionAPI } from "@earendil-works/pi-coding-agent";\nimport { createDeckDelegateTool } from ${JSON.stringify(path.resolve(delegateExtensionPath))};\n\nconst marker = "PI_DECK_E2E_INVOKE_DECK_DELEGATE";\n\nexport default function deckDelegateAcceptanceHarness(pi: ExtensionAPI): void {\n  pi.on("before_agent_start", async (event) => {\n    if (!event.prompt.includes(marker)) return undefined;\n    const result = await createDeckDelegateTool(pi).execute(\n      "pi-deck-e2e-delegate",\n      { action: "delegate", name: "Real delegated acceptance task", task: "Reply with exactly: PI_DECK_REAL_DELEGATE_OK" },\n      new AbortController().signal,\n    );\n    pi.sendMessage({ customType: "deck_delegate_acceptance", content: "Deck delegate acceptance result: " + result.content.map((part) => part.type === "text" ? part.text : "").join(""), display: true });\n    return undefined;\n  });\n}\n`,
    "utf8",
  );
}

/** Self-contained TypeScript source written by {@link writeDeckDelegateExtension}. */
export const DECK_DELEGATE_EXTENSION_SOURCE = String.raw`// Generated by Pi Deck. Load explicitly with: pi --extension ./deck-delegate.ts
// Deck delegate JSONL protocol v1. The endpoint is supplied by Deck; this file does not implement it.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import net, { type Socket } from "node:net";

export const DECK_DELEGATE_PROTOCOL_VERSION = 1;
export const DECK_DELEGATE_ENDPOINT_ENV = "DECK_DELEGATE_ENDPOINT";
export const DECK_DELEGATE_CAPABILITY_ENV = "DECK_DELEGATE_CAPABILITY";
export const DECK_DELEGATE_PARENT_RUNTIME_ENV = "DECK_DELEGATE_PARENT_RUNTIME";
const MAX_LINE_BYTES = 64 * 1024;
const MAX_BUFFER_BYTES = MAX_LINE_BYTES + 1;
const MAX_TASK_CHARS = 32 * 1024;
const MAX_NAME_CHARS = 256;
const CONNECT_TIMEOUT_MS = 30_000;

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export interface DeckDelegateRequest {
  version: 1;
  type: "delegate";
  capability: string;
  toolCallId: string;
  task: string;
  name?: string;
  action?: "provide_input";
  taskNumber?: number;
  input?: string;
}
export interface DeckDelegateLifecycleMessage {
  version: 1;
  type: "lifecycle";
  toolCallId: string;
  taskNumber?: number;
  status: "started" | "progress" | "input-needed";
  message?: string;
}
export interface DeckDelegateResultMessage {
  version: 1;
  type: "result";
  toolCallId: string;
  ok: boolean;
  text: string;
  details?: JsonValue;
}
export interface DeckDelegateModeQuery {
  version: 1;
  type: "mode-query";
  requestId: string;
}
export interface DeckDelegateModeState {
  version: 1;
  type: "mode-state";
  requestId: string;
  mode: "sequential" | "parallel";
}
export type DeckDelegateWireMessage = DeckDelegateRequest | DeckDelegateLifecycleMessage | DeckDelegateResultMessage;

type Endpoint = { kind: "tcp"; port: number } | { kind: "unix"; path: string };

function configuration(): { endpoint: Endpoint; capability: string; parentRuntimeId: string } {
  const rawEndpoint = process.env[DECK_DELEGATE_ENDPOINT_ENV];
  const capability = process.env[DECK_DELEGATE_CAPABILITY_ENV];
  const parentRuntimeId = process.env[DECK_DELEGATE_PARENT_RUNTIME_ENV];
  if (!rawEndpoint || !parentRuntimeId || parentRuntimeId.length > 256) throw new Error("Deck delegate endpoint is not configured");
  // Capabilities are opaque printable tokens; reject whitespace/control characters so they cannot frame JSONL.
  if (!capability || capability.length < 16 || capability.length > 512 || !/^[!-~]+$/.test(capability)) {
    throw new Error("Deck delegate capability is missing or invalid");
  }
  const tcp = /^tcp:127\.0\.0\.1:([0-9]{1,5})$/.exec(rawEndpoint);
  if (tcp) {
    const port = Number(tcp[1]);
    if (port >= 1 && port <= 65535) return { endpoint: { kind: "tcp", port }, capability, parentRuntimeId }; 
  }
  if (rawEndpoint.startsWith("unix:/") && rawEndpoint.length <= 4096 && !/[\r\n\0]/.test(rawEndpoint)) {
    return { endpoint: { kind: "unix", path: rawEndpoint.slice("unix:".length) }, capability, parentRuntimeId };
  }
  throw new Error("Deck delegate endpoint must be tcp:127.0.0.1:<port> or unix:/<path>");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function lifecycle(value: unknown, toolCallId: string): DeckDelegateLifecycleMessage | undefined {
  if (!isRecord(value) || value.version !== 1 || value.type !== "lifecycle" || value.toolCallId !== toolCallId) return undefined;
  if (value.status !== "started" && value.status !== "progress" && value.status !== "input-needed") return undefined;
  if (value.taskNumber !== undefined && (!Number.isSafeInteger(value.taskNumber) || value.taskNumber < 1)) return undefined;
  if (value.message !== undefined && (typeof value.message !== "string" || value.message.length > MAX_TASK_CHARS)) return undefined;
  return value as DeckDelegateLifecycleMessage;
}

function result(value: unknown, toolCallId: string): DeckDelegateResultMessage | undefined {
  if (!isRecord(value) || value.version !== 1 || value.type !== "result" || value.toolCallId !== toolCallId) return undefined;
  if (typeof value.ok !== "boolean" || typeof value.text !== "string" || value.text.length > MAX_TASK_CHARS) return undefined;
  return value as DeckDelegateResultMessage;
}

function writeJsonLine(socket: Socket, value: unknown): void {
  const encoded = Buffer.from(JSON.stringify(value) + "\n", "utf8");
  if (encoded.byteLength > MAX_LINE_BYTES) throw new Error("Delegate request exceeds JSONL size limit");
  socket.write(encoded);
}

function relay(pi: ExtensionAPI, message: DeckDelegateLifecycleMessage | DeckDelegateResultMessage): void {
  const inputNeeded = message.type === "lifecycle" && message.status === "input-needed";
  const text = message.type === "result" ? message.text : (message.message || message.status);
  const taskNumber = message.type === "lifecycle" ? message.taskNumber : undefined;
  try {
    pi.sendMessage({
      customType: "deck_delegate",
      content: (inputNeeded ? "Deck child task #" + taskNumber + " needs input: " : "Deck child result: ") + text + (inputNeeded ? ". Ask the user, then call deck_delegate with action provide_input, this taskNumber, and their answer." : ""),
      display: true,
      details: { version: 1, type: message.type, status: message.type === "lifecycle" ? message.status : undefined, taskNumber, ok: message.type === "result" ? message.ok : undefined },
    }, { deliverAs: "steer", triggerTurn: true });
  } catch {
    // A relay failure must not orphan or change the actual delegate result.
  }
}

let nextModeQueryId = 1;

/** Fetch mode anew for each turn; the capability determines the parent runtime. */
function queryMode(endpoint: Endpoint, capability: string): Promise<"sequential" | "parallel"> {
  return new Promise((resolve, reject) => {
    const socket = endpoint.kind === "tcp"
      ? net.createConnection({ host: "127.0.0.1", port: endpoint.port })
      : net.createConnection({ path: endpoint.path });
    const requestId = "mode-" + nextModeQueryId++;
    let buffer = Buffer.alloc(0);
    let authenticated = false;
    let settled = false;
    const timer = setTimeout(() => fail(new Error("Deck mode query timed out")), CONNECT_TIMEOUT_MS);
    const cleanup = () => { clearTimeout(timer); socket.removeAllListeners(); if (!socket.destroyed) socket.destroy(); };
    const fail = (error: Error) => { if (!settled) { settled = true; cleanup(); reject(error); } };
    const succeed = (mode: "sequential" | "parallel") => { if (!settled) { settled = true; cleanup(); resolve(mode); } };
    socket.once("connect", () => { try { writeJsonLine(socket, { version: 1, type: "authenticate", token: capability }); } catch (error) { fail(error instanceof Error ? error : new Error("Unable to authenticate mode query")); } });
    socket.on("data", (chunk: Buffer) => {
      buffer = Buffer.concat([buffer, chunk]);
      if (buffer.byteLength > MAX_BUFFER_BYTES) return fail(new Error("Deck mode query buffer exceeds size limit"));
      const newline = buffer.indexOf(10);
      if (newline < 0) return;
      const line = buffer.subarray(0, newline);
      if (line.byteLength > MAX_LINE_BYTES) return fail(new Error("Deck mode query line exceeds size limit"));
      let value: unknown;
      try { value = JSON.parse(line.toString("utf8")); } catch { return fail(new Error("Deck mode query sent invalid JSONL")); }
      if (!authenticated) {
        if (!isRecord(value) || value.version !== 1 || value.type !== "authenticated") return fail(new Error("Deck mode query authentication failed"));
        authenticated = true;
        try { writeJsonLine(socket, { version: 1, type: "mode-query", requestId }); } catch (error) { fail(error instanceof Error ? error : new Error("Unable to query Deck mode")); }
        return;
      }
      if (!isRecord(value) || value.version !== 1 || value.type !== "mode-state" || value.requestId !== requestId || (value.mode !== "sequential" && value.mode !== "parallel")) return fail(new Error("Deck mode query sent an invalid protocol message"));
      succeed(value.mode);
    });
    socket.once("error", (error) => fail(error));
    socket.once("close", () => { if (!settled) fail(new Error("Deck mode query connection closed")); });
  });
}

function delegate(pi: ExtensionAPI, request: DeckDelegateRequest, endpoint: Endpoint, signal: AbortSignal): Promise<DeckDelegateResultMessage> {
  return new Promise((resolve, reject) => {
    const socket = endpoint.kind === "tcp"
      ? net.createConnection({ host: "127.0.0.1", port: endpoint.port })
      : net.createConnection({ path: endpoint.path });
    let buffer = Buffer.alloc(0);
    let settled = false;
    const timer = setTimeout(() => fail(new Error("Deck delegate connection timed out")), CONNECT_TIMEOUT_MS);
    const cleanup = () => {
      clearTimeout(timer);
      signal.removeEventListener("abort", aborted);
      socket.removeAllListeners();
      if (!socket.destroyed) socket.destroy();
    };
    const succeed = (message: DeckDelegateResultMessage) => {
      if (settled) return;
      settled = true;
      cleanup();
      relay(pi, message);
      resolve(message);
    };
    const fail = (error: Error) => {
      if (settled) return;
      settled = true;
      cleanup();
      reject(error);
    };
    const aborted = () => fail(new Error("Deck delegate cancelled"));
    const onData = (chunk: Buffer) => {
      buffer = Buffer.concat([buffer, chunk]);
      if (buffer.byteLength > MAX_BUFFER_BYTES) return fail(new Error("Deck delegate JSONL buffer exceeds size limit"));
      for (;;) {
        const newline = buffer.indexOf(10);
        if (newline < 0) return;
        const line = buffer.subarray(0, newline);
        buffer = buffer.subarray(newline + 1);
        if (line.byteLength > MAX_LINE_BYTES) return fail(new Error("Deck delegate JSONL line exceeds size limit"));
        let parsed: unknown;
        try { parsed = JSON.parse(line.toString("utf8")); } catch { return fail(new Error("Deck delegate sent invalid JSONL")); }
        if (!authenticated) {
          if (isRecord(parsed) && parsed.version === 1 && parsed.type === "authenticated") {
            authenticated = true;
            try { writeJsonLine(socket, { version: 1, type: "delegate", toolCallId: request.toolCallId, payload: { task: request.task, parentRuntimeId: process.env[DECK_DELEGATE_PARENT_RUNTIME_ENV], ...(request.name ? { name: request.name } : {}), ...(request.action === "provide_input" ? { action: "provide_input", taskNumber: request.taskNumber, input: request.input } : {}) } }); } catch (error) { return fail(error instanceof Error ? error : new Error("Unable to send Deck delegate")); }
            continue;
          }
          return fail(new Error("Deck delegate authentication failed"));
        }
        const event = isRecord(parsed) && parsed.version === 1 && parsed.type === "child-lifecycle" && parsed.toolCallId === request.toolCallId && Number.isSafeInteger(parsed.taskNumber) && (parsed.taskNumber as number) > 0
          ? { status: parsed.status, taskNumber: parsed.taskNumber as number } : undefined;
        if (event) {
          if (event.status === "waiting-input") relay(pi, { version: 1, type: "lifecycle", toolCallId: request.toolCallId, taskNumber: event.taskNumber, status: "input-needed", message: "Child needs input" });
          continue;
        }
        const final = isRecord(parsed) && parsed.version === 1 && parsed.type === "child-result" && parsed.toolCallId === request.toolCallId
          ? { version: 1 as const, type: "result" as const, toolCallId: request.toolCallId, ok: parsed.outcome === "completed", text: isRecord(parsed.handoff) && typeof parsed.handoff.summary === "string" ? parsed.handoff.summary : (parsed.outcome === "completed" ? "Child completed" : "Child failed") }
          : undefined;
        if (final) return succeed(final);
        return fail(new Error("Deck delegate sent an invalid protocol message"));
      }
    };
    let authenticated = false;
    socket.once("connect", () => {
      try { writeJsonLine(socket, { version: 1, type: "authenticate", token: request.capability }); } catch (error) { fail(error instanceof Error ? error : new Error("Unable to authenticate Deck delegate")); }
    });
    socket.on("data", onData);
    socket.once("error", (error) => fail(error));
    socket.once("close", () => { if (!settled) fail(new Error("Deck delegate connection closed without a result")); });
    signal.addEventListener("abort", aborted, { once: true });
    if (signal.aborted) aborted();
  });
}

export function createDeckDelegateTool(pi: ExtensionAPI) {
  return {
    name: "deck_delegate",
    label: "Delegate to Deck child",
    description: "Delegate an interactive child task to Pi Deck.",
    parameters: Type.Object({
      action: Type.Optional(Type.Union([Type.Literal("delegate"), Type.Literal("provide_input")])),
      task: Type.Optional(Type.String({ minLength: 1, maxLength: MAX_TASK_CHARS, description: "Task for a new Deck child" })),
      name: Type.Optional(Type.String({ minLength: 1, maxLength: MAX_NAME_CHARS, description: "Optional child name" })),
      taskNumber: Type.Optional(Type.Integer({ minimum: 1, description: "Task number from the input-needed notification" })),
      input: Type.Optional(Type.String({ minLength: 1, maxLength: MAX_TASK_CHARS, description: "User answer for that child" })),
    }),
    async execute(toolCallId: string, params: { action?: "delegate" | "provide_input"; task?: string; name?: string; taskNumber?: number; input?: string }, signal: AbortSignal) {
      try {
        const config = configuration();
        const action = params.action || "delegate";
        const task = action === "provide_input"
          ? undefined
          : (typeof params.task === "string" ? params.task : undefined);
        if (action === "delegate" && !task) throw new Error("task is required when delegating");
        if (action === "provide_input" && (!params.taskNumber || !params.input)) throw new Error("taskNumber and input are required when providing input");
        const request: DeckDelegateRequest = { version: 1, type: "delegate", capability: config.capability, toolCallId, task: task || "", ...(params.name ? { name: params.name } : {}) };
        // The authenticated bridge maps this supported tool action by public task number.
        if (action === "provide_input") {
          request.action = "provide_input";
          request.taskNumber = params.taskNumber!;
          request.input = params.input!;
        }
        const final = await delegate(pi, request, config.endpoint, signal);
        return { content: [{ type: "text" as const, text: final.text }], details: { ok: final.ok, serverDetails: final.details } };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Deck delegate failed";
        return { content: [{ type: "text" as const, text: "Deck delegation failed: " + message }], details: { ok: false, error: message } };
      }
    },
  };
}

export default function deckDelegateExtension(pi: ExtensionAPI): void {
  pi.registerCommand("deck-task-prompt", {
    description: "Record a Pi Deck task-session prompt without starting a parent turn.",
    handler: async (args) => {
      try {
        const decoded = Buffer.from(args.trim(), "base64url").toString("utf8");
        const payload = JSON.parse(decoded) as { prompt?: unknown };
        if (typeof payload.prompt !== "string" || !payload.prompt.trim() || payload.prompt.length > MAX_TASK_CHARS) {
          throw new Error("invalid task-session prompt");
        }
        const prompt = payload.prompt.trim();
        pi.appendEntry("deck_task_prompt", { prompt });
        if (!pi.getSessionName()) pi.setSessionName(prompt.slice(0, MAX_NAME_CHARS));
      } catch {
        throw new Error("Pi Deck task-session prompt could not be recorded");
      }
    },
  });

  // This hook runs before each agent start. It queries Deck over the
  // capability-bound bridge rather than inferring mode from conversation text.
  pi.on("before_agent_start", async (event) => {
    try {
      const config = configuration();
      const mode = await queryMode(config.endpoint, config.capability);
      const instruction = mode === "parallel"
        ? "Pi Deck manages Parallel mode task-session planning and routing outside this parent turn. Do not call deck_delegate for ordinary user prompts; the tool remains available only for an explicit compatibility-bridge invocation."
        : "Pi Deck Parallel mode is off. Do not call deck_delegate; handle the work in this parent session.";
      return { systemPrompt: event.systemPrompt + "\n\n" + instruction };
    } catch {
      // A failed mode lookup must not invent delegation permission.
      return undefined;
    }
  });

  pi.registerTool(createDeckDelegateTool(pi));
}
`;
